<?php
declare(strict_types=1);

/**
 * Permisiunile modulului "Dispecer curse" (?page=dispecer_curse).
 *
 * Cheile modulului si ale actiunilor sunt STABILE: sunt salvate in access_permissions.
 * Eticheta, descrierea, sectiunea si grupul se pot schimba oricand. Vezi permissions/README.md.
 */
return [
    'key'         => 'dispecer_curse',
    'label'       => 'Dispecer curse',
    'description' => 'Gestionare curse, refacturări și documente',
    'section'     => 'operational',
    'icon'        => 'bi-truck',
    'order'       => 90,
    'scope'       => 'all',
    'groups'      => [
        'operare'     => 'Operare',
        'facturare'   => 'Facturare',
        'stergere'    => 'Ștergere și recuperare',
        'configurare' => 'Configurare',
    ],
    'actions'     => [
        'view'               => ['label' => 'Vizualizare listă & KPI'],
        'create'             => ['label' => 'Creare cursă', 'group' => 'operare'],
        'edit'               => ['label' => 'Editare cursă', 'group' => 'operare'],
        'delete'             => ['label' => 'Ștergere cursă', 'group' => 'stergere'],
        'delete_bulk'        => ['label' => 'Ștergere în masă', 'group' => 'stergere'],
        'billing_status'     => ['label' => 'Schimbare status facturare', 'group' => 'facturare'],
        'expenses'           => ['label' => 'Cheltuieli cursă & documente', 'group' => 'operare'],
        'service_km'         => ['label' => 'Km service (vehicul la reparat)', 'group' => 'operare'],
        'refacturari_view'   => ['label' => 'Refacturări — vizualizare', 'group' => 'facturare'],
        'refacturari_manage' => ['label' => 'Creare / marcare refacturare', 'group' => 'facturare'],
        'deleted_view'       => ['label' => 'Curse șterse — vizualizare', 'group' => 'stergere', 'admin_only' => true],
        'restore'            => ['label' => 'Restaurare cursă ștearsă', 'group' => 'stergere', 'admin_only' => true],
        'config'             => ['label' => 'Configurare (locații, zone, rute, catalog, beneficiari)', 'group' => 'configurare', 'admin_only' => true],
    ],
    'endpoints'   => [
        'store'                        => 'create',
        'edit'                         => 'edit',
        'update'                       => 'edit',
        'segment_store'                => 'edit',
        'segment_update'               => 'edit',
        'segment_delete'               => 'edit',
        'request_diurna_change'        => 'edit',
        'delete'                       => 'delete',
        'delete_bulk'                  => 'delete_bulk',
        'service_km_store'             => 'service_km',
        'service_km_delete'            => 'service_km',
        'save_expense'                 => 'expenses',
        'delete_expense'               => 'expenses',
        'update_expense_status'        => 'expenses',
        'update_status'                => 'billing_status',
        'refacturari'                  => 'refacturari_view',
        'refacturari_export'           => 'refacturari_view',
        'store_refacturare'            => 'refacturari_manage',
        'toggle_refacturare_facturata' => 'refacturari_manage',
        'bulk_refacturari'             => 'refacturari_manage',
        'curse_sterse'                 => 'deleted_view',
        'curse_sterse_details'         => 'deleted_view',
        'restore_cursa'                => 'restore',
        'delete_cursa_stearsa'         => 'restore',
        'config'                       => 'config',
        'config_v2'                    => 'config',
        'config_store_distributie'     => 'config',
        'config_store_primar_ruta'     => 'config',
        'config_store_catalog'         => 'config',
        'config_delete_ruta'           => 'config',
        'config_delete_ruta_primar'    => 'config',
        'config_store_loc'             => 'config',
        'config_delete_loc'            => 'config',
        'config_store_zona'            => 'config',
        'config_delete_zona'           => 'config',
        'config_store_beneficiar'      => 'config',
        'config_delete_beneficiar'     => 'config',
        'config_delete_beneficiari'    => 'config',
    ],
];
