CREATE TABLE IF NOT EXISTS supplier_invoices (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    supplier_id INT UNSIGNED NULL,
    supplier_name VARCHAR(190) NULL,
    invoice_number VARCHAR(120) NOT NULL,
    invoice_date DATE NOT NULL,
    due_date DATE NULL,
    pdf_path VARCHAR(255) NULL,
    status ENUM('draft','in_progress','finalizata','anulata') NOT NULL DEFAULT 'finalizata',
    notes TEXT NULL,
    labour_total DECIMAL(12,2) NOT NULL DEFAULT 0,
    parts_subtotal DECIMAL(12,2) NOT NULL DEFAULT 0,
    vat_total DECIMAL(12,2) NOT NULL DEFAULT 0,
    parts_total DECIMAL(12,2) NOT NULL DEFAULT 0,
    grand_total DECIMAL(12,2) NOT NULL DEFAULT 0,
    source_maintenance_id INT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uk_supplier_invoices_number (invoice_number),
    UNIQUE KEY uk_supplier_invoices_source (source_maintenance_id),
    INDEX idx_supplier_invoices_supplier (supplier_id),
    INDEX idx_supplier_invoices_date (invoice_date),
    INDEX idx_supplier_invoices_status (status),
    CONSTRAINT fk_supplier_invoices_source_maintenance FOREIGN KEY (source_maintenance_id) REFERENCES mentenanta(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS invoice_vehicle_repairs (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    invoice_id INT UNSIGNED NOT NULL,
    vehicle_id INT UNSIGNED NOT NULL,
    km_at_repair INT UNSIGNED NULL,
    defect TEXT NULL,
    component_group_id INT UNSIGNED NULL,
    technical_category_id INT UNSIGNED NULL,
    technical_component_id INT UNSIGNED NULL,
    repair_description TEXT NULL,
    repair_status ENUM('in_asteptare','in_lucru','finalizata','anulata') NOT NULL DEFAULT 'finalizata',
    immobilization_days DECIMAL(6,2) NOT NULL DEFAULT 0,
    condition_after_percent TINYINT UNSIGNED NULL,
    labour_supplier_id INT UNSIGNED NULL,
    labour_supplier_name VARCHAR(190) NULL,
    labour_cost DECIMAL(12,2) NOT NULL DEFAULT 0,
    source_maintenance_id INT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_invoice_repairs_invoice (invoice_id),
    INDEX idx_invoice_repairs_vehicle (vehicle_id),
    INDEX idx_invoice_repairs_source (source_maintenance_id),
    CONSTRAINT fk_invoice_repairs_invoice FOREIGN KEY (invoice_id) REFERENCES supplier_invoices(id) ON DELETE CASCADE,
    CONSTRAINT fk_invoice_repairs_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicule(id) ON DELETE CASCADE,
    CONSTRAINT fk_invoice_repairs_source_maintenance FOREIGN KEY (source_maintenance_id) REFERENCES mentenanta(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS invoice_repair_parts (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    repair_id INT UNSIGNED NOT NULL,
    part_name VARCHAR(190) NOT NULL,
    part_code VARCHAR(100) NULL,
    stock_part_id INT UNSIGNED NULL,
    quantity DECIMAL(12,2) NOT NULL DEFAULT 1,
    unit_price_without_vat DECIMAL(12,2) NOT NULL DEFAULT 0,
    discount_percent DECIMAL(5,2) NOT NULL DEFAULT 0,
    value_without_vat DECIMAL(12,2) NOT NULL DEFAULT 0,
    vat_percent DECIMAL(5,2) NOT NULL DEFAULT 0,
    vat_value DECIMAL(12,2) NOT NULL DEFAULT 0,
    total_with_vat DECIMAL(12,2) NOT NULL DEFAULT 0,
    part_supplier_id INT UNSIGNED NULL,
    part_supplier_name VARCHAR(190) NULL,
    notes TEXT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_invoice_parts_repair (repair_id),
    INDEX idx_invoice_parts_stock (stock_part_id),
    INDEX idx_invoice_parts_supplier (part_supplier_id),
    CONSTRAINT fk_invoice_parts_repair FOREIGN KEY (repair_id) REFERENCES invoice_vehicle_repairs(id) ON DELETE CASCADE,
    CONSTRAINT fk_invoice_parts_stock FOREIGN KEY (stock_part_id) REFERENCES mentenanta_piese(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
