<?php
declare(strict_types=1);

return [
    'vehicule' => [
        'title' => 'Vehicule',
        'singular' => 'vehicul',
        'table' => 'vehicule',
        // Exclude internal technical row used by tire stock bookkeeping.
        'base_conditions' => [
            "t.nr_inmatriculare <> 'STOC-ANVELOPE'",
            "t.serie_sasiu <> 'STOCANVELOPE00001'",
        ],
        'select' => 't.*',
        'default_order' => 't.created_at DESC',
        'search_mode' => 'vehicle_plate',
        'search_fields' => ['t.nr_inmatriculare', 't.marca', 't.model', 't.tip_vehicul', 't.serie_sasiu', 't.nr_fabricatie', 't.formula_axelor', 't.organism_notificat', 't.garaj', 't.observatii'],
        'list_columns' => [
            'poza_original' => ['label' => 'Foto', 'type' => 'vehicle_photo'],
            'nr_inmatriculare' => ['label' => 'Nr. inmatriculare'],
            'marca' => ['label' => 'Marca'],
            'model' => ['label' => 'Model'],
            'tip_vehicul' => ['label' => 'Tip vehicul', 'type' => 'vehicle_type'],
            'cuplaj_curent' => ['label' => 'Cuplat cu'],
            'an_fabricatie' => ['label' => 'An fabricatie', 'type' => 'year'],
            'km_bord' => ['label' => 'Km bord', 'type' => 'integer'],
            'km_revizie' => ['label' => 'Km revizie', 'type' => 'integer'],
            'serie_sasiu' => ['label' => 'Serie sasiu'],
            'garaj' => ['label' => 'Garaj'],
            'status' => ['label' => 'Status', 'type' => 'status'],
            'updated_at' => ['label' => 'Actualizat la', 'type' => 'datetime'],
        ],
        'detail_fields' => [
            'poza_original' => ['label' => 'Poza vehicul', 'type' => 'vehicle_photo_detail'],
            'nr_inmatriculare' => ['label' => 'Nr. inmatriculare'],
            'marca' => ['label' => 'Marca'],
            'model' => ['label' => 'Model'],
            'tip_vehicul' => ['label' => 'Tip vehicul', 'type' => 'vehicle_type'],
            'cuplaj_curent' => ['label' => 'Cuplat cu'],
            'an_fabricatie' => ['label' => 'An fabricatie', 'type' => 'year'],
            'km_bord' => ['label' => 'Km bord', 'type' => 'integer'],
            'km_revizie' => ['label' => 'Km revizie', 'type' => 'integer'],
            'nr_fabricatie' => ['label' => 'Nr. fabricatie'],
            'serie_sasiu' => ['label' => 'Serie sasiu'],
            'capacitate_transport' => ['label' => 'Capacitate transport (tone)', 'type' => 'number', 'decimals' => 2],
            'formula_axelor' => ['label' => 'Formula axelor'],
            'capacitate_rezervor' => ['label' => 'Capacitate rezervor (litri)', 'type' => 'number', 'decimals' => 2],
            'mma' => ['label' => 'MMA (kg)', 'type' => 'number', 'decimals' => 2],
            'organism_notificat' => ['label' => 'Organism notificat'],
            'garaj' => ['label' => 'Garaj'],
            'status' => ['label' => 'Status', 'type' => 'status'],
            'observatii' => ['label' => 'Observatii', 'type' => 'textarea'],
            'created_at' => ['label' => 'Creat la', 'type' => 'datetime'],
            'updated_at' => ['label' => 'Actualizat la', 'type' => 'datetime'],
        ],
        'form_fields' => [
            'nr_inmatriculare' => ['label' => 'Nr. inmatriculare', 'type' => 'text', 'required' => true, 'maxlength' => 20],
            'marca' => ['label' => 'Marca', 'type' => 'text', 'required' => true, 'maxlength' => 50],
            'model' => ['label' => 'Model', 'type' => 'text', 'required' => true, 'maxlength' => 50],
            'tip_vehicul' => [
                'label' => 'Tip vehicul',
                'type' => 'select',
                'required' => true,
                'options' => [
                    'cap_tractor' => 'Cap tractor',
                    'semiremorca_primar' => 'Semi-remorca primar',
                    'semiremorca_distributie' => 'Semi-remorca distributie',
                    'camion' => 'Camion',
                    'autovehicul' => 'Autoturism',
                    'autoutilitara' => 'Autoutilitara',
                ],
                'default' => 'autovehicul',
            ],
            'an_fabricatie' => ['label' => 'An fabricatie', 'type' => 'number', 'required' => true, 'min' => 1950, 'max' => 2100, 'integer' => true],
            'km_bord' => [
                'label' => 'Km bord',
                'type' => 'number',
                'required' => true,
                'min' => 0,
                'integer' => true,
                'placeholder' => 'Ex: 245000',
                'help' => 'Introdu kilometrajul curent al vehiculului la momentul inregistrarii.',
            ],
            'km_revizie' => [
                'label' => 'Km revizie',
                'type' => 'number',
                'required' => true,
                'min' => 0,
                'integer' => true,
                'placeholder' => 'Ex: 260000',
                'help' => 'Introdu kilometrul la care este planificata urmatoarea revizie.',
            ],
            'serie_sasiu' => [
                'label' => 'Serie sasiu',
                'type' => 'text',
                'required' => true,
                'maxlength' => 17,
                'minlength' => 17,
                'exactlength' => 17,
                'uppercase' => true,
                'remove_spaces' => true,
                'placeholder' => 'Ex: WF0XXXTTGXLA02021',
                'help' => 'Seria de sasiu trebuie sa contina exact 17 caractere.',
            ],
            'nr_fabricatie' => [
                'label' => 'Nr. fabricatie',
                'type' => 'text',
                'required' => false,
                'nullable' => true,
                'maxlength' => 100,
                'placeholder' => 'Ex: FAB-2026-001',
            ],
            'capacitate_transport' => [
                'label' => 'Capacitate transport (tone)',
                'type' => 'number',
                'required' => false,
                'nullable' => true,
                'min' => 0,
                'step' => '0.01',
            ],
            'formula_axelor' => [
                'label' => 'Formula axelor',
                'type' => 'text',
                'required' => false,
                'nullable' => true,
                'maxlength' => 20,
                'placeholder' => '-- Selecteaza formula axelor --',
                'help' => 'Camion: 4x2, 6x2, 8x2. Cap tractor: 4x2, 6x2, 6x4, 8x4. Semi-remorca: 2/3/4/6 axe (2 anvelope/axa). Autoturism/Autoutilitara: 2 axe / 4x2.',
            ],
            'capacitate_rezervor' => [
                'label' => 'Capacitate rezervor (litri)',
                'type' => 'number',
                'required' => false,
                'nullable' => true,
                'min' => 0,
                'step' => '0.01',
            ],
            'mma' => [
                'label' => 'MMA (kg)',
                'type' => 'number',
                'required' => false,
                'nullable' => true,
                'min' => 0,
                'step' => '0.01',
            ],
            'organism_notificat' => [
                'label' => 'Organism notificat',
                'type' => 'text',
                'required' => false,
                'nullable' => true,
                'maxlength' => 150,
                'placeholder' => 'Ex: RAR',
            ],
            'garaj' => [
                'label' => 'Garaj',
                'type' => 'text',
                'required' => false,
                'nullable' => true,
                'maxlength' => 120,
                'placeholder' => 'Ex: Garaj Bucuresti Nord',
            ],
            'poza_upload' => [
                'label' => 'Poza vehicul',
                'type' => 'file',
                'required' => false,
                'store' => false,
                'accept' => '.jpg,.jpeg,.png,.webp',
                'allowed_extensions' => ['jpg', 'jpeg', 'png', 'webp'],
                'max_size' => 5242880,
                'help' => 'Formate acceptate: JPG, PNG, WEBP. Dimensiune maxima: 5 MB.',
                'original_field' => 'poza_original',
                'stored_field' => 'poza_stocata',
                'remove_field' => 'sterge_poza',
                'preview_type' => 'vehicle_photo',
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'required' => true,
                'options' => ['activ' => 'Activ', 'inactiv' => 'Inactiv'],
                'default' => 'activ',
            ],
            'observatii' => ['label' => 'Observatii', 'type' => 'textarea', 'required' => false, 'nullable' => true],
        ],
        'filters' => [
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'column' => 't.status',
                'operator' => '=',
                'options' => ['activ' => 'Activ', 'inactiv' => 'Inactiv'],
            ],
            'tip_vehicul' => [
                'label' => 'Tip vehicul',
                'type' => 'multiselect',
                'column' => 't.tip_vehicul',
                'operator' => '=',
                'options' => [
                    'cap_tractor' => 'Cap tractor',
                    'semiremorca_primar' => 'Semi-remorca primar',
                    'semiremorca_distributie' => 'Semi-remorca distributie',
                    'camion' => 'Camion',
                    'autovehicul' => 'Autoturism',
                    'autoutilitara' => 'Autoutilitara',
                ],
            ],
        ],
        'unique_fields' => [
            ['field' => 'nr_inmatriculare', 'column' => 'nr_inmatriculare'],
        ],
    ],
    'soferi' => [
        'title' => 'ÃˆËœoferi',
        'singular' => 'Ãˆâ„¢ofer',
        'table' => 'soferi',
        'select' => "t.*,
            COALESCE(NULLIF(driver_vehicle_labels.vehicul_label, ''), '-') AS vehicul_label,
            COALESCE(driver_vehicle_labels.vehicul_model, '') AS vehicul_model",
        'joins' => [
            ['type' => 'LEFT', 'table' => "(SELECT
                    sv.driver_id,
                    GROUP_CONCAT(
                        CASE
                            WHEN vs.id IS NULL THEN v.nr_inmatriculare
                            ELSE CONCAT(v.nr_inmatriculare, ' + ', vs.nr_inmatriculare)
                        END
                        ORDER BY sv.is_primary DESC, v.nr_inmatriculare ASC
                        SEPARATOR ', '
                    ) AS vehicul_label,
                    GROUP_CONCAT(
                        TRIM(CONCAT(COALESCE(v.marca, ''), ' ', COALESCE(v.model, '')))
                        ORDER BY sv.is_primary DESC, v.nr_inmatriculare ASC
                        SEPARATOR ', '
                    ) AS vehicul_model
                FROM soferi_vehicule sv
                INNER JOIN vehicule v ON v.id = sv.vehicle_id
                LEFT JOIN (SELECT tractor_id, MAX(id) AS last_id FROM vehicule_cuplaje WHERE activ = 1 GROUP BY tractor_id) vc_latest ON vc_latest.tractor_id = v.id
                LEFT JOIN vehicule_cuplaje vc ON vc.id = vc_latest.last_id
                LEFT JOIN vehicule vs ON vs.id = vc.semiremorca_id
                GROUP BY sv.driver_id) driver_vehicle_labels", 'on' => 'driver_vehicle_labels.driver_id = t.id'],
        ],
        'default_order' => 't.created_at DESC',
        'search_fields' => ['t.nume', 't.telefon', 't.observatii', 'driver_vehicle_labels.vehicul_label', 'driver_vehicle_labels.vehicul_model'],
        'list_columns' => [
            'poza_original' => ['label' => 'Foto', 'type' => 'driver_photo'],
            'nume' => ['label' => 'Nume'],
            'data_nasterii' => ['label' => 'Data nasterii', 'type' => 'date'],
            'telefon' => ['label' => 'Telefon'],
            'vehicul_label' => ['label' => 'Vehicule alocate'],
            'status' => ['label' => 'Status', 'type' => 'status'],
            'updated_at' => ['label' => 'Actualizat la', 'type' => 'datetime'],
        ],
        'detail_fields' => [
            'poza_original' => ['label' => 'Poza sofer', 'type' => 'driver_photo_detail'],
            'nume' => ['label' => 'Nume'],
            'data_nasterii' => ['label' => 'Data nasterii', 'type' => 'date'],
            'telefon' => ['label' => 'Telefon'],
            'vehicul_label' => ['label' => 'Vehicule alocate'],
            'status' => ['label' => 'Status', 'type' => 'status'],
            'observatii' => ['label' => 'ObservaÃˆâ€ºii', 'type' => 'textarea'],
            'created_at' => ['label' => 'Creat la', 'type' => 'datetime'],
            'updated_at' => ['label' => 'Actualizat la', 'type' => 'datetime'],
        ],
        'form_fields' => [
            'nume' => ['label' => 'Nume', 'type' => 'text', 'required' => true, 'maxlength' => 100],
            'data_nasterii' => ['label' => 'Data nasterii', 'type' => 'date', 'required' => false, 'nullable' => true],
            'telefon' => ['label' => 'Telefon', 'type' => 'text', 'required' => true, 'maxlength' => 20],
            'vehicle_ids' => [
                'label' => 'Vehicule alocate',
                'type' => 'multiselect',
                'required' => false,
                'nullable' => true,
                'store' => false,
                'default' => [],
                'source' => [
                    'table' => 'vehicule',
                    'value' => 'id',
                    'label' => "CONCAT(
                        nr_inmatriculare,
                        ' - ',
                        marca,
                        ' ',
                        model,
                        IF(
                            tip_vehicul = 'cap_tractor',
                            IFNULL(
                                CONCAT(
                                    ' + ',
                                    (
                                        SELECT s.nr_inmatriculare
                                        FROM vehicule_cuplaje vc
                                        INNER JOIN vehicule s ON s.id = vc.semiremorca_id
                                        WHERE vc.tractor_id = vehicule.id
                                          AND vc.activ = 1
                                        ORDER BY vc.id DESC
                                        LIMIT 1
                                    )
                                ),
                                ''
                            ),
                            ''
                        )
                    )",
                    'where' => "status = 'activ' AND tip_vehicul NOT IN ('semiremorca', 'semiremorca_primar', 'semiremorca_distributie')",
                    'order' => 'nr_inmatriculare ASC',
                ],
                'help' => 'Deschide lista si bifeaza toate vehiculele pe care vrei sa le aloci soferului.',
                'placeholder' => '-- Selecteaza vehiculele --',
                'summary_singular' => 'vehicul selectat',
                'summary_plural' => 'vehicule selectate',
            ],
            'poza_upload' => [
                'label' => 'Poza sofer',
                'type' => 'file',
                'required' => false,
                'store' => false,
                'accept' => '.jpg,.jpeg,.png,.webp',
                'allowed_extensions' => ['jpg', 'jpeg', 'png', 'webp'],
                'max_size' => 5242880,
                'help' => 'Formate acceptate: JPG, PNG, WEBP. Dimensiune maxima: 5 MB.',
                'original_field' => 'poza_original',
                'stored_field' => 'poza_stocata',
                'remove_field' => 'sterge_poza',
                'preview_type' => 'driver_photo',
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'required' => true,
                'options' => ['activ' => 'Activ', 'inactiv' => 'Inactiv'],
                'default' => 'activ',
            ],
            'observatii' => ['label' => 'ObservaÃˆâ€ºii', 'type' => 'textarea', 'required' => false, 'nullable' => true],
        ],
        'filters' => [
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'column' => 't.status',
                'operator' => '=',
                'options' => ['activ' => 'Activ', 'inactiv' => 'Inactiv'],
            ],
        ],
    ],

    'mentenanta' => [
        'title' => 'MentenanÃˆâ€ºÃ„Æ’',
        'singular' => 'intervenÃˆâ€ºie',
        'table' => 'mentenanta',
        'select' => 't.*, v.nr_inmatriculare AS vehicul_label, CONCAT(v.marca, " ", v.model) AS vehicul_model',
        'joins' => [
            ['type' => 'INNER', 'table' => 'vehicule v', 'on' => 'v.id = t.vehicle_id'],
        ],
        'default_order' => 't.data_interventie DESC, t.id DESC',
        'search_fields' => ['v.nr_inmatriculare', 't.tip_interventie', 't.atelier', 't.furnizor_piesa', 't.observatii'],
        'list_columns' => [
            'data_interventie' => ['label' => 'Data intervenÃˆâ€ºie', 'type' => 'date'],
            'vehicul_label' => ['label' => 'Vehicul'],
            'tip_interventie' => ['label' => 'Tip intervenÃˆâ€ºie'],
            'cost' => ['label' => 'Cost', 'type' => 'currency'],
            'atelier' => ['label' => 'Atelier'],
            'furnizor_piesa' => ['label' => 'Furnizor piesa'],
            'observatii' => ['label' => 'Observatii'],
        ],
        'detail_fields' => [
            'vehicul_label' => ['label' => 'Vehicul'],
            'tip_interventie' => ['label' => 'Tip intervenÃˆâ€ºie'],
            'data_interventie' => ['label' => 'Data intervenÃˆâ€ºie', 'type' => 'date'],
            'cost' => ['label' => 'Cost', 'type' => 'currency'],
            'atelier' => ['label' => 'Atelier'],
            'furnizor_piesa' => ['label' => 'Furnizor piesa'],
            'observatii' => ['label' => 'ObservaÃˆâ€ºii', 'type' => 'textarea'],
            'created_at' => ['label' => 'Creat la', 'type' => 'datetime'],
            'updated_at' => ['label' => 'Actualizat la', 'type' => 'datetime'],
        ],
        'form_fields' => [
            'vehicle_id' => [
                'label' => 'Vehicul',
                'type' => 'select',
                'required' => true,
                'source' => [
                    'table' => 'vehicule',
                    'value' => 'id',
                    'label' => "CONCAT(nr_inmatriculare, ' - ', marca, ' ', model)",
                    'order' => 'nr_inmatriculare ASC',
                ],
            ],
            'tip_interventie' => ['label' => 'Tip intervenÃˆâ€ºie', 'type' => 'text', 'required' => true, 'maxlength' => 150],
            'data_interventie' => ['label' => 'Data intervenÃˆâ€ºie', 'type' => 'date', 'required' => true],
            'cost' => ['label' => 'Cost (lei)', 'type' => 'number', 'required' => true, 'min' => 0, 'step' => '0.01'],
            'atelier' => ['label' => 'Atelier', 'type' => 'text', 'required' => false, 'nullable' => true, 'maxlength' => 120],
            'observatii' => ['label' => 'ObservaÃˆâ€ºii', 'type' => 'textarea', 'required' => false, 'nullable' => true],
        ],
        'filters' => [
            'vehicle_id' => [
                'label' => 'Vehicul',
                'type' => 'select',
                'column' => 't.vehicle_id',
                'operator' => '=',
                'source' => [
                    'table' => 'vehicule',
                    'value' => 'id',
                    'label' => "CONCAT(nr_inmatriculare, ' - ', marca, ' ', model)",
                    'order' => 'nr_inmatriculare ASC',
                ],
            ],
            'data_start' => ['label' => 'Data de la', 'type' => 'date', 'column' => 't.data_interventie', 'operator' => '>='],
            'data_end' => ['label' => 'Data pÃƒÂ¢nÃ„Æ’ la', 'type' => 'date', 'column' => 't.data_interventie', 'operator' => '<='],
        ],
    ],

    'documente' => [
        'title' => 'Documente Vehicule',
        'singular' => 'document vehicul',
        'table' => 'documente',
        'select' => 't.*, DATEDIFF(t.data_expirare, CURDATE()) AS zile_expirare, v.nr_inmatriculare AS vehicul_label, CONCAT(v.marca, " ", v.model) AS vehicul_model',
        'joins' => [
            ['type' => 'INNER', 'table' => 'vehicule v', 'on' => 'v.id = t.vehicle_id'],
        ],
        'default_order' => 't.data_expirare IS NULL ASC, t.data_expirare ASC, t.id DESC',
        'search_fields' => ['v.nr_inmatriculare', 't.tip_document', 't.numar_document', 't.observatii', 't.fisier_original'],
        'list_columns' => [
            'vehicul_label' => ['label' => 'Vehicul'],
            'tip_document' => ['label' => 'Tip document'],
            'numar_document' => ['label' => 'NumÃ„Æ’r document'],
            'fisier_original' => ['label' => 'FiÃˆâ„¢ier', 'type' => 'document_file'],
            'data_expirare' => ['label' => 'Data expirare', 'type' => 'expiry'],
            'zile_expirare' => ['label' => 'Zile expirare', 'type' => 'integer'],
            'updated_at' => ['label' => 'Actualizat la', 'type' => 'datetime'],
        ],
        'detail_fields' => [
            'vehicul_label' => ['label' => 'Vehicul'],
            'tip_document' => ['label' => 'Tip document'],
            'numar_document' => ['label' => 'NumÃ„Æ’r document'],
            'data_expirare' => ['label' => 'Data expirare', 'type' => 'expiry'],
            'observatii' => ['label' => 'ObservaÃˆâ€ºii', 'type' => 'textarea'],
            'created_at' => ['label' => 'Creat la', 'type' => 'datetime'],
            'updated_at' => ['label' => 'Actualizat la', 'type' => 'datetime'],
        ],
        'form_fields' => [
            'vehicle_id' => [
                'label' => 'Vehicul',
                'type' => 'select',
                'required' => true,
                'source' => [
                    'table' => 'vehicule',
                    'value' => 'id',
                    'label' => "CONCAT(nr_inmatriculare, ' - ', marca, ' ', model)",
                    'order' => 'nr_inmatriculare ASC',
                ],
            ],
            'tip_document' => ['label' => 'Tip document', 'type' => 'select', 'required' => true],
            'numar_document' => ['label' => 'NumÃ„Æ’r document', 'type' => 'text', 'required' => true, 'maxlength' => 100],
            'data_expirare' => ['label' => 'Data expirare', 'type' => 'date', 'required' => true],
            'observatii' => ['label' => 'ObservaÃˆâ€ºii', 'type' => 'textarea', 'required' => false, 'nullable' => true],
        ],
        'filters' => [
            'vehicle_id' => [
                'label' => 'Vehicul',
                'type' => 'select',
                'column' => 't.vehicle_id',
                'operator' => '=',
                'source' => [
                    'table' => 'vehicule',
                    'value' => 'id',
                    'label' => "CONCAT(nr_inmatriculare, ' - ', marca, ' ', model)",
                    'order' => 'nr_inmatriculare ASC',
                ],
            ],
            'data_start' => ['label' => 'ExpirÃ„Æ’ de la', 'type' => 'date', 'column' => 't.data_expirare', 'operator' => '>='],
            'data_end' => ['label' => 'ExpirÃ„Æ’ pÃƒÂ¢nÃ„Æ’ la', 'type' => 'date', 'column' => 't.data_expirare', 'operator' => '<='],
        ],
        'nav_parent' => 'vehicule',
    ],

    'configurare_costuri_documente_vehicule_override' => [
        'title' => 'Configurare Costuri',
        'singular' => 'configurare cost document vehicul',
        'table' => 'configurare_costuri_documente_vehicule_override',
        'select' => 't.*, v.nr_inmatriculare AS vehicul_label, v.tip_vehicul AS vehicul_type',
        'joins' => [
            ['type' => 'INNER', 'table' => 'vehicule v', 'on' => 'v.id = t.vehicle_id'],
        ],
        'base_conditions' => [
            "v.nr_inmatriculare <> 'STOC-ANVELOPE'",
            "v.serie_sasiu <> 'STOCANVELOPE00001'",
        ],
        'default_order' => 'v.nr_inmatriculare ASC, t.document_type ASC',
        'admin_only' => true,
        'search_fields' => ['v.nr_inmatriculare', 'v.marca', 'v.model', 't.document_type'],
        'list_columns' => [
            'vehicul_label' => ['label' => 'Vehicul'],
            'vehicul_type' => ['label' => 'Tip vehicul', 'type' => 'vehicle_type'],
            'document_type' => ['label' => 'Tip document'],
            'document_cost' => ['label' => 'Cost document (lei)', 'type' => 'currency'],
            'validity_days' => ['label' => 'Valabilitate (zile)', 'type' => 'integer'],
            'updated_at' => ['label' => 'Actualizat la', 'type' => 'datetime'],
        ],
        'detail_fields' => [
            'vehicul_label' => ['label' => 'Vehicul'],
            'vehicul_type' => ['label' => 'Tip vehicul', 'type' => 'vehicle_type'],
            'document_type' => ['label' => 'Tip document'],
            'document_cost' => ['label' => 'Cost document (lei)', 'type' => 'currency'],
            'validity_days' => ['label' => 'Valabilitate (zile)', 'type' => 'integer'],
            'created_at' => ['label' => 'Creat la', 'type' => 'datetime'],
            'updated_at' => ['label' => 'Actualizat la', 'type' => 'datetime'],
        ],
        'form_fields' => [
            'vehicle_id' => [
                'label' => 'Vehicul',
                'type' => 'select',
                'required' => true,
                'source' => [
                    'table' => 'vehicule',
                    'value' => 'id',
                    'label' => "CONCAT(nr_inmatriculare, ' - ', marca, ' ', model)",
                    'where' => "nr_inmatriculare <> 'STOC-ANVELOPE' AND serie_sasiu <> 'STOCANVELOPE00001'",
                    'order' => 'nr_inmatriculare ASC',
                ],
            ],
            'document_type' => [
                'label' => 'Tip document',
                'type' => 'select',
                'required' => true,
                'placeholder' => 'Selecteaza vehiculul mai intai',
            ],
            'document_cost' => [
                'label' => 'Cost document (lei)',
                'type' => 'number',
                'required' => true,
                'min' => 0,
                'step' => '0.01',
            ],
            'validity_days' => [
                'label' => 'Valabilitate (zile)',
                'type' => 'number',
                'required' => true,
                'integer' => true,
                'min' => 1,
                'placeholder' => 'Ex: 365',
            ],
        ],
        'filters' => [
            'vehicle_id' => [
                'label' => 'Vehicul',
                'type' => 'select',
                'column' => 't.vehicle_id',
                'operator' => '=',
                'source' => [
                    'table' => 'vehicule',
                    'value' => 'id',
                    'label' => "CONCAT(nr_inmatriculare, ' - ', marca, ' ', model)",
                    'where' => "nr_inmatriculare <> 'STOC-ANVELOPE' AND serie_sasiu <> 'STOCANVELOPE00001'",
                    'order' => 'nr_inmatriculare ASC',
                ],
            ],
        ],
    ],

    'configurare_costuri_documente_soferi' => [
        'title' => 'Configurare Costuri',
        'singular' => 'configurare cost document sofer',
        'table' => 'configurare_costuri_documente_soferi',
        'select' => 't.*, s.nume AS sofer_label, s.telefon AS sofer_telefon, v.nr_inmatriculare AS vehicul_label',
        'joins' => [
            ['type' => 'INNER', 'table' => 'soferi s', 'on' => 's.id = t.driver_id'],
            ['type' => 'LEFT', 'table' => 'vehicule v', 'on' => 'v.id = s.vehicle_id'],
        ],
        'default_order' => 's.nume ASC, t.document_type ASC',
        'admin_only' => true,
        'search_fields' => ['s.nume', 's.telefon', 'v.nr_inmatriculare', 't.document_type'],
        'list_columns' => [
            'sofer_label' => ['label' => 'Sofer'],
            'vehicul_label' => ['label' => 'Vehicul alocat'],
            'document_type' => ['label' => 'Tip document'],
            'document_cost' => ['label' => 'Cost document (lei)', 'type' => 'currency'],
            'validity_days' => ['label' => 'Valabilitate (zile)', 'type' => 'integer'],
            'updated_at' => ['label' => 'Actualizat la', 'type' => 'datetime'],
        ],
        'detail_fields' => [
            'sofer_label' => ['label' => 'Sofer'],
            'sofer_telefon' => ['label' => 'Telefon sofer'],
            'vehicul_label' => ['label' => 'Vehicul alocat'],
            'document_type' => ['label' => 'Tip document'],
            'document_cost' => ['label' => 'Cost document (lei)', 'type' => 'currency'],
            'validity_days' => ['label' => 'Valabilitate (zile)', 'type' => 'integer'],
            'created_at' => ['label' => 'Creat la', 'type' => 'datetime'],
            'updated_at' => ['label' => 'Actualizat la', 'type' => 'datetime'],
        ],
        'form_fields' => [
            'driver_id' => [
                'label' => 'Sofer',
                'type' => 'select',
                'required' => true,
                'source' => [
                    'table' => 'soferi',
                    'value' => 'id',
                    'label' => "CONCAT(nume, ' - ', telefon)",
                    'order' => 'nume ASC',
                ],
            ],
            'document_type' => [
                'label' => 'Tip document',
                'type' => 'select',
                'required' => true,
                'placeholder' => 'Selecteaza soferul mai intai',
            ],
            'document_cost' => [
                'label' => 'Cost document (lei)',
                'type' => 'number',
                'required' => true,
                'min' => 0,
                'step' => '0.01',
            ],
            'validity_days' => [
                'label' => 'Valabilitate (zile)',
                'type' => 'number',
                'required' => true,
                'integer' => true,
                'min' => 1,
                'placeholder' => 'Ex: 365',
            ],
        ],
        'filters' => [
            'driver_id' => [
                'label' => 'Sofer',
                'type' => 'select',
                'column' => 't.driver_id',
                'operator' => '=',
                'source' => [
                    'table' => 'soferi',
                    'value' => 'id',
                    'label' => 'nume',
                    'order' => 'nume ASC',
                ],
            ],
        ],
        'nav_parent' => 'configurare_costuri_documente_vehicule_override',
    ],

    'documente_soferi' => [
        'title' => 'Documente Ãˆâ„¢oferi',
        'singular' => 'document Ãˆâ„¢ofer',
        'table' => 'documente_soferi',
        'select' => 't.*, s.nume AS sofer_label, s.telefon AS sofer_telefon, v.nr_inmatriculare AS vehicul_label',
        'joins' => [
            ['type' => 'INNER', 'table' => 'soferi s', 'on' => 's.id = t.driver_id'],
            ['type' => 'LEFT', 'table' => 'vehicule v', 'on' => 'v.id = s.vehicle_id'],
        ],
        'default_order' => 't.data_expirare IS NULL ASC, t.data_expirare ASC, t.id DESC',
        'search_fields' => ['s.nume', 's.telefon', 't.tip_document', 't.numar_document', 't.observatii', 't.fisier_original'],
        'list_columns' => [
            'sofer_label' => ['label' => 'ÃˆËœofer'],
            'vehicul_label' => ['label' => 'Vehicul alocat'],
            'tip_document' => ['label' => 'Tip document'],
            'numar_document' => ['label' => 'NumÃ„Æ’r document'],
            'fisier_original' => ['label' => 'FiÃˆâ„¢ier', 'type' => 'document_file'],
            'data_expirare' => ['label' => 'Data expirare', 'type' => 'expiry'],
            'updated_at' => ['label' => 'Actualizat la', 'type' => 'datetime'],
        ],
        'detail_fields' => [
            'sofer_label' => ['label' => 'ÃˆËœofer'],
            'sofer_telefon' => ['label' => 'Telefon Ãˆâ„¢ofer'],
            'vehicul_label' => ['label' => 'Vehicul alocat'],
            'tip_document' => ['label' => 'Tip document'],
            'numar_document' => ['label' => 'NumÃ„Æ’r document'],
            'data_expirare' => ['label' => 'Data expirare', 'type' => 'expiry'],
            'observatii' => ['label' => 'ObservaÃˆâ€ºii', 'type' => 'textarea'],
            'created_at' => ['label' => 'Creat la', 'type' => 'datetime'],
            'updated_at' => ['label' => 'Actualizat la', 'type' => 'datetime'],
        ],
        'form_fields' => [
            'driver_id' => [
                'label' => 'ÃˆËœofer',
                'type' => 'select',
                'required' => true,
                'source' => [
                    'table' => 'soferi',
                    'value' => 'id',
                    'label' => "CONCAT(nume, ' - ', telefon)",
                    'order' => 'nume ASC',
                ],
            ],
            'tip_document' => [
                'label' => 'Tip document',
                'type' => 'select',
                'required' => true,
                'placeholder' => 'Selecteaza tipul de document',
            ],
            'numar_document' => ['label' => 'NumÃ„Æ’r document', 'type' => 'text', 'required' => false, 'nullable' => true, 'maxlength' => 100],
            'data_expirare' => ['label' => 'Data expirare', 'type' => 'date', 'required' => true],
            'observatii' => ['label' => 'ObservaÃˆâ€ºii', 'type' => 'textarea', 'required' => false, 'nullable' => true],
        ],
        'filters' => [
            'driver_id' => [
                'label' => 'ÃˆËœofer',
                'type' => 'select',
                'column' => 't.driver_id',
                'operator' => '=',
                'source' => [
                    'table' => 'soferi',
                    'value' => 'id',
                    'label' => 'nume',
                    'order' => 'nume ASC',
                ],
            ],
            'data_start' => ['label' => 'ExpirÃ„Æ’ de la', 'type' => 'date', 'column' => 't.data_expirare', 'operator' => '>='],
            'data_end' => ['label' => 'ExpirÃ„Æ’ pÃƒÂ¢nÃ„Æ’ la', 'type' => 'date', 'column' => 't.data_expirare', 'operator' => '<='],
        ],
        'nav_parent' => 'soferi',
    ],

    'utilizatori' => [
        'title' => 'Utilizatori',
        'singular' => 'utilizator',
        'table' => 'utilizatori',
        'select' => 't.*',
        'default_order' => 't.created_at DESC',
        'admin_only' => true,
        'search_fields' => ['t.nume', 't.email'],
        'list_columns' => [
            'nume' => ['label' => 'Nume'],
            'email' => ['label' => 'Email'],
            'rol' => ['label' => 'Rol', 'type' => 'role'],
            'status' => ['label' => 'Status', 'type' => 'status'],
            'updated_at' => ['label' => 'Actualizat la', 'type' => 'datetime'],
        ],
        'detail_fields' => [
            'nume' => ['label' => 'Nume'],
            'email' => ['label' => 'Email'],
            'rol' => ['label' => 'Rol', 'type' => 'role'],
            'status' => ['label' => 'Status', 'type' => 'status'],
            'created_at' => ['label' => 'Creat la', 'type' => 'datetime'],
            'updated_at' => ['label' => 'Actualizat la', 'type' => 'datetime'],
        ],
        'form_fields' => [
            'nume' => ['label' => 'Nume', 'type' => 'text', 'required' => true, 'maxlength' => 120],
            'email' => ['label' => 'Email', 'type' => 'email', 'required' => true, 'maxlength' => 190],
            'parola' => ['label' => 'ParolÃ„Æ’', 'type' => 'password', 'required_on' => 'create', 'minlength' => 8, 'hash' => true],
            'confirmare_parola' => [
                'label' => 'Confirmare parolÃ„Æ’',
                'type' => 'password',
                'required_on' => 'create',
                'store' => false,
                'matches' => 'parola',
            ],
            'rol' => [
                'label' => 'Rol',
                'type' => 'select',
                'required' => true,
                'options' => ['admin' => 'Admin', 'contabilitate' => 'Contabilitate', 'utilizator' => 'Operator'],
                'default' => 'utilizator',
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'required' => true,
                'options' => ['activ' => 'Activ', 'inactiv' => 'Inactiv'],
                'default' => 'activ',
            ],
        ],
        'filters' => [
            'rol' => [
                'label' => 'Rol',
                'type' => 'select',
                'column' => 't.rol',
                'operator' => '=',
                'options' => ['admin' => 'Admin', 'contabilitate' => 'Contabilitate', 'utilizator' => 'Operator'],
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'column' => 't.status',
                'operator' => '=',
                'options' => ['activ' => 'Activ', 'inactiv' => 'Inactiv'],
            ],
        ],
        'unique_fields' => [
            ['field' => 'email', 'column' => 'email'],
        ],
    ],
];
